server {
    listen 80;
    root /usr/share/nginx/html;
    location / {
        try_files $uri /index.html;
    }
    location /api/ {
        proxy_pass http://ob-viewer-api:8090/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
