// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PrivateAccountV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public interface PrivateAccountV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrivateAccountV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vcoinName = 1;</code>
   * @return The vcoinName.
   */
  java.lang.String getVcoinName();
  /**
   * <code>string vcoinName = 1;</code>
   * @return The bytes for vcoinName.
   */
  com.google.protobuf.ByteString
      getVcoinNameBytes();

  /**
   * <code>string coinId = 2;</code>
   * @return The coinId.
   */
  java.lang.String getCoinId();
  /**
   * <code>string coinId = 2;</code>
   * @return The bytes for coinId.
   */
  com.google.protobuf.ByteString
      getCoinIdBytes();

  /**
   * <code>string balanceAmount = 3;</code>
   * @return The balanceAmount.
   */
  java.lang.String getBalanceAmount();
  /**
   * <code>string balanceAmount = 3;</code>
   * @return The bytes for balanceAmount.
   */
  com.google.protobuf.ByteString
      getBalanceAmountBytes();

  /**
   * <code>string balanceAmountChange = 4;</code>
   * @return The balanceAmountChange.
   */
  java.lang.String getBalanceAmountChange();
  /**
   * <code>string balanceAmountChange = 4;</code>
   * @return The bytes for balanceAmountChange.
   */
  com.google.protobuf.ByteString
      getBalanceAmountChangeBytes();

  /**
   * <code>string frozenAmount = 5;</code>
   * @return The frozenAmount.
   */
  java.lang.String getFrozenAmount();
  /**
   * <code>string frozenAmount = 5;</code>
   * @return The bytes for frozenAmount.
   */
  com.google.protobuf.ByteString
      getFrozenAmountBytes();

  /**
   * <code>string frozenAmountChange = 6;</code>
   * @return The frozenAmountChange.
   */
  java.lang.String getFrozenAmountChange();
  /**
   * <code>string frozenAmountChange = 6;</code>
   * @return The bytes for frozenAmountChange.
   */
  com.google.protobuf.ByteString
      getFrozenAmountChangeBytes();

  /**
   * <code>string type = 7;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 7;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int64 time = 8;</code>
   * @return The time.
   */
  long getTime();
}
