// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicMiniTickersV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicMiniTickersV3Api}
 */
@com.google.protobuf.Generated
public final class PublicMiniTickersV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicMiniTickersV3Api)
    PublicMiniTickersV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PublicMiniTickersV3Api");
  }
  // Use PublicMiniTickersV3Api.newBuilder() to construct.
  private PublicMiniTickersV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicMiniTickersV3Api() {
    items_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mxc.push.common.protobuf.PublicMiniTickersV3ApiProto.internal_static_PublicMiniTickersV3Api_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mxc.push.common.protobuf.PublicMiniTickersV3ApiProto.internal_static_PublicMiniTickersV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mxc.push.common.protobuf.PublicMiniTickersV3Api.class, com.mxc.push.common.protobuf.PublicMiniTickersV3Api.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.mxc.push.common.protobuf.PublicMiniTickerV3Api> items_;
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.mxc.push.common.protobuf.PublicMiniTickerV3Api> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicMiniTickerV3Api getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mxc.push.common.protobuf.PublicMiniTickersV3Api)) {
      return super.equals(obj);
    }
    com.mxc.push.common.protobuf.PublicMiniTickersV3Api other = (com.mxc.push.common.protobuf.PublicMiniTickersV3Api) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mxc.push.common.protobuf.PublicMiniTickersV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicMiniTickersV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicMiniTickersV3Api)
      com.mxc.push.common.protobuf.PublicMiniTickersV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mxc.push.common.protobuf.PublicMiniTickersV3ApiProto.internal_static_PublicMiniTickersV3Api_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mxc.push.common.protobuf.PublicMiniTickersV3ApiProto.internal_static_PublicMiniTickersV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mxc.push.common.protobuf.PublicMiniTickersV3Api.class, com.mxc.push.common.protobuf.PublicMiniTickersV3Api.Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicMiniTickersV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mxc.push.common.protobuf.PublicMiniTickersV3ApiProto.internal_static_PublicMiniTickersV3Api_descriptor;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicMiniTickersV3Api getDefaultInstanceForType() {
      return com.mxc.push.common.protobuf.PublicMiniTickersV3Api.getDefaultInstance();
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicMiniTickersV3Api build() {
      com.mxc.push.common.protobuf.PublicMiniTickersV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicMiniTickersV3Api buildPartial() {
      com.mxc.push.common.protobuf.PublicMiniTickersV3Api result = new com.mxc.push.common.protobuf.PublicMiniTickersV3Api(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.mxc.push.common.protobuf.PublicMiniTickersV3Api result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(com.mxc.push.common.protobuf.PublicMiniTickersV3Api result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mxc.push.common.protobuf.PublicMiniTickersV3Api) {
        return mergeFrom((com.mxc.push.common.protobuf.PublicMiniTickersV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mxc.push.common.protobuf.PublicMiniTickersV3Api other) {
      if (other == com.mxc.push.common.protobuf.PublicMiniTickersV3Api.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.mxc.push.common.protobuf.PublicMiniTickerV3Api m =
                  input.readMessage(
                      com.mxc.push.common.protobuf.PublicMiniTickerV3Api.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.mxc.push.common.protobuf.PublicMiniTickerV3Api> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.mxc.push.common.protobuf.PublicMiniTickerV3Api>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.mxc.push.common.protobuf.PublicMiniTickerV3Api, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder, com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public java.util.List<com.mxc.push.common.protobuf.PublicMiniTickerV3Api> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder setItems(
        int index, com.mxc.push.common.protobuf.PublicMiniTickerV3Api value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder setItems(
        int index, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder addItems(com.mxc.push.common.protobuf.PublicMiniTickerV3Api value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder addItems(
        int index, com.mxc.push.common.protobuf.PublicMiniTickerV3Api value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder addItems(
        com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder addItems(
        int index, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.mxc.push.common.protobuf.PublicMiniTickerV3Api> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder getItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public java.util.List<? extends com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder addItemsBuilder() {
      return internalGetItemsFieldBuilder().addBuilder(
          com.mxc.push.common.protobuf.PublicMiniTickerV3Api.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder addItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().addBuilder(
          index, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
     */
    public java.util.List<com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder> 
         getItemsBuilderList() {
      return internalGetItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.mxc.push.common.protobuf.PublicMiniTickerV3Api, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder, com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder> 
        internalGetItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.mxc.push.common.protobuf.PublicMiniTickerV3Api, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder, com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:PublicMiniTickersV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicMiniTickersV3Api)
  private static final com.mxc.push.common.protobuf.PublicMiniTickersV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mxc.push.common.protobuf.PublicMiniTickersV3Api();
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickersV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicMiniTickersV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicMiniTickersV3Api>() {
    @java.lang.Override
    public PublicMiniTickersV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicMiniTickersV3Api> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublicMiniTickersV3Api> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicMiniTickersV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

