// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicBookTickerBatchV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public interface PublicBookTickerBatchV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicBookTickerBatchV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  java.util.List<com.mxc.push.common.protobuf.PublicBookTickerV3Api> 
      getItemsList();
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicBookTickerV3Api getItems(int index);
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  java.util.List<? extends com.mxc.push.common.protobuf.PublicBookTickerV3ApiOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicBookTickerV3ApiOrBuilder getItemsOrBuilder(
      int index);
}
