// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicMiniTickersV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public interface PublicMiniTickersV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicMiniTickersV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  java.util.List<com.mxc.push.common.protobuf.PublicMiniTickerV3Api> 
      getItemsList();
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicMiniTickerV3Api getItems(int index);
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  java.util.List<? extends com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .PublicMiniTickerV3Api items = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder getItemsOrBuilder(
      int index);
}
