// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDepthsV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicAggreDepthsV3Api}
 */
@com.google.protobuf.Generated
public final class PublicAggreDepthsV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicAggreDepthsV3Api)
    PublicAggreDepthsV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PublicAggreDepthsV3Api");
  }
  // Use PublicAggreDepthsV3Api.newBuilder() to construct.
  private PublicAggreDepthsV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicAggreDepthsV3Api() {
    asks_ = java.util.Collections.emptyList();
    bids_ = java.util.Collections.emptyList();
    eventType_ = "";
    fromVersion_ = "";
    toVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mxc.push.common.protobuf.PublicAggreDepthsV3ApiProto.internal_static_PublicAggreDepthsV3Api_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mxc.push.common.protobuf.PublicAggreDepthsV3ApiProto.internal_static_PublicAggreDepthsV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.class, com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.Builder.class);
  }

  public static final int ASKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> asks_;
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> getAsksList() {
    return asks_;
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> 
      getAsksOrBuilderList() {
    return asks_;
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  @java.lang.Override
  public int getAsksCount() {
    return asks_.size();
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem getAsks(int index) {
    return asks_.get(index);
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
   */
  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder getAsksOrBuilder(
      int index) {
    return asks_.get(index);
  }

  public static final int BIDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> bids_;
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> getBidsList() {
    return bids_;
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> 
      getBidsOrBuilderList() {
    return bids_;
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  @java.lang.Override
  public int getBidsCount() {
    return bids_.size();
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem getBids(int index) {
    return bids_.get(index);
  }
  /**
   * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
   */
  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder getBidsOrBuilder(
      int index) {
    return bids_.get(index);
  }

  public static final int EVENTTYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventType_ = "";
  /**
   * <code>string eventType = 3;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <code>string eventType = 3;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMVERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fromVersion_ = "";
  /**
   * <code>string fromVersion = 4;</code>
   * @return The fromVersion.
   */
  @java.lang.Override
  public java.lang.String getFromVersion() {
    java.lang.Object ref = fromVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string fromVersion = 4;</code>
   * @return The bytes for fromVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromVersionBytes() {
    java.lang.Object ref = fromVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOVERSION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toVersion_ = "";
  /**
   * <code>string toVersion = 5;</code>
   * @return The toVersion.
   */
  @java.lang.Override
  public java.lang.String getToVersion() {
    java.lang.Object ref = toVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string toVersion = 5;</code>
   * @return The bytes for toVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToVersionBytes() {
    java.lang.Object ref = toVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < asks_.size(); i++) {
      output.writeMessage(1, asks_.get(i));
    }
    for (int i = 0; i < bids_.size(); i++) {
      output.writeMessage(2, bids_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, fromVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, toVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < asks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, asks_.get(i));
    }
    for (int i = 0; i < bids_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, bids_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, fromVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, toVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mxc.push.common.protobuf.PublicAggreDepthsV3Api)) {
      return super.equals(obj);
    }
    com.mxc.push.common.protobuf.PublicAggreDepthsV3Api other = (com.mxc.push.common.protobuf.PublicAggreDepthsV3Api) obj;

    if (!getAsksList()
        .equals(other.getAsksList())) return false;
    if (!getBidsList()
        .equals(other.getBidsList())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getFromVersion()
        .equals(other.getFromVersion())) return false;
    if (!getToVersion()
        .equals(other.getToVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAsksCount() > 0) {
      hash = (37 * hash) + ASKS_FIELD_NUMBER;
      hash = (53 * hash) + getAsksList().hashCode();
    }
    if (getBidsCount() > 0) {
      hash = (37 * hash) + BIDS_FIELD_NUMBER;
      hash = (53 * hash) + getBidsList().hashCode();
    }
    hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + FROMVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getFromVersion().hashCode();
    hash = (37 * hash) + TOVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getToVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mxc.push.common.protobuf.PublicAggreDepthsV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicAggreDepthsV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicAggreDepthsV3Api)
      com.mxc.push.common.protobuf.PublicAggreDepthsV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mxc.push.common.protobuf.PublicAggreDepthsV3ApiProto.internal_static_PublicAggreDepthsV3Api_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mxc.push.common.protobuf.PublicAggreDepthsV3ApiProto.internal_static_PublicAggreDepthsV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.class, com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
      } else {
        asks_ = null;
        asksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
      } else {
        bids_ = null;
        bidsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      eventType_ = "";
      fromVersion_ = "";
      toVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mxc.push.common.protobuf.PublicAggreDepthsV3ApiProto.internal_static_PublicAggreDepthsV3Api_descriptor;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicAggreDepthsV3Api getDefaultInstanceForType() {
      return com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.getDefaultInstance();
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicAggreDepthsV3Api build() {
      com.mxc.push.common.protobuf.PublicAggreDepthsV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicAggreDepthsV3Api buildPartial() {
      com.mxc.push.common.protobuf.PublicAggreDepthsV3Api result = new com.mxc.push.common.protobuf.PublicAggreDepthsV3Api(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.mxc.push.common.protobuf.PublicAggreDepthsV3Api result) {
      if (asksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          asks_ = java.util.Collections.unmodifiableList(asks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.asks_ = asks_;
      } else {
        result.asks_ = asksBuilder_.build();
      }
      if (bidsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          bids_ = java.util.Collections.unmodifiableList(bids_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.bids_ = bids_;
      } else {
        result.bids_ = bidsBuilder_.build();
      }
    }

    private void buildPartial0(com.mxc.push.common.protobuf.PublicAggreDepthsV3Api result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.eventType_ = eventType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fromVersion_ = fromVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.toVersion_ = toVersion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mxc.push.common.protobuf.PublicAggreDepthsV3Api) {
        return mergeFrom((com.mxc.push.common.protobuf.PublicAggreDepthsV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mxc.push.common.protobuf.PublicAggreDepthsV3Api other) {
      if (other == com.mxc.push.common.protobuf.PublicAggreDepthsV3Api.getDefaultInstance()) return this;
      if (asksBuilder_ == null) {
        if (!other.asks_.isEmpty()) {
          if (asks_.isEmpty()) {
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAsksIsMutable();
            asks_.addAll(other.asks_);
          }
          onChanged();
        }
      } else {
        if (!other.asks_.isEmpty()) {
          if (asksBuilder_.isEmpty()) {
            asksBuilder_.dispose();
            asksBuilder_ = null;
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            asksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAsksFieldBuilder() : null;
          } else {
            asksBuilder_.addAllMessages(other.asks_);
          }
        }
      }
      if (bidsBuilder_ == null) {
        if (!other.bids_.isEmpty()) {
          if (bids_.isEmpty()) {
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBidsIsMutable();
            bids_.addAll(other.bids_);
          }
          onChanged();
        }
      } else {
        if (!other.bids_.isEmpty()) {
          if (bidsBuilder_.isEmpty()) {
            bidsBuilder_.dispose();
            bidsBuilder_ = null;
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000002);
            bidsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetBidsFieldBuilder() : null;
          } else {
            bidsBuilder_.addAllMessages(other.bids_);
          }
        }
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getFromVersion().isEmpty()) {
        fromVersion_ = other.fromVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getToVersion().isEmpty()) {
        toVersion_ = other.toVersion_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem m =
                  input.readMessage(
                      com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.parser(),
                      extensionRegistry);
              if (asksBuilder_ == null) {
                ensureAsksIsMutable();
                asks_.add(m);
              } else {
                asksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem m =
                  input.readMessage(
                      com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.parser(),
                      extensionRegistry);
              if (bidsBuilder_ == null) {
                ensureBidsIsMutable();
                bids_.add(m);
              } else {
                bidsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              fromVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              toVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> asks_ =
      java.util.Collections.emptyList();
    private void ensureAsksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        asks_ = new java.util.ArrayList<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem>(asks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> asksBuilder_;

    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> getAsksList() {
      if (asksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(asks_);
      } else {
        return asksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public int getAsksCount() {
      if (asksBuilder_ == null) {
        return asks_.size();
      } else {
        return asksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem getAsks(int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);
      } else {
        return asksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder setAsks(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.set(index, value);
        onChanged();
      } else {
        asksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder setAsks(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.set(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(value);
        onChanged();
      } else {
        asksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(index, value);
        onChanged();
      } else {
        asksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(
        com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAsks(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder addAllAsks(
        java.lang.Iterable<? extends com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> values) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, asks_);
        onChanged();
      } else {
        asksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder clearAsks() {
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        asksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public Builder removeAsks(int index) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.remove(index);
        onChanged();
      } else {
        asksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder getAsksBuilder(
        int index) {
      return internalGetAsksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder getAsksOrBuilder(
        int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);  } else {
        return asksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public java.util.List<? extends com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> 
         getAsksOrBuilderList() {
      if (asksBuilder_ != null) {
        return asksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(asks_);
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder addAsksBuilder() {
      return internalGetAsksFieldBuilder().addBuilder(
          com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder addAsksBuilder(
        int index) {
      return internalGetAsksFieldBuilder().addBuilder(
          index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem asks = 1;</code>
     */
    public java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder> 
         getAsksBuilderList() {
      return internalGetAsksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> 
        internalGetAsksFieldBuilder() {
      if (asksBuilder_ == null) {
        asksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder>(
                asks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        asks_ = null;
      }
      return asksBuilder_;
    }

    private java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> bids_ =
      java.util.Collections.emptyList();
    private void ensureBidsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        bids_ = new java.util.ArrayList<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem>(bids_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> bidsBuilder_;

    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> getBidsList() {
      if (bidsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bids_);
      } else {
        return bidsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public int getBidsCount() {
      if (bidsBuilder_ == null) {
        return bids_.size();
      } else {
        return bidsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem getBids(int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);
      } else {
        return bidsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder setBids(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.set(index, value);
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder setBids(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.set(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(index, value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(
        com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder addBids(
        int index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder addAllBids(
        java.lang.Iterable<? extends com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem> values) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bids_);
        onChanged();
      } else {
        bidsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder clearBids() {
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        bidsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public Builder removeBids(int index) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.remove(index);
        onChanged();
      } else {
        bidsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder getBidsBuilder(
        int index) {
      return internalGetBidsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder getBidsOrBuilder(
        int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);  } else {
        return bidsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public java.util.List<? extends com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> 
         getBidsOrBuilderList() {
      if (bidsBuilder_ != null) {
        return bidsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bids_);
      }
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder addBidsBuilder() {
      return internalGetBidsFieldBuilder().addBuilder(
          com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder addBidsBuilder(
        int index) {
      return internalGetBidsFieldBuilder().addBuilder(
          index, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.getDefaultInstance());
    }
    /**
     * <code>repeated .PublicAggreDepthV3ApiItem bids = 2;</code>
     */
    public java.util.List<com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder> 
         getBidsBuilderList() {
      return internalGetBidsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder> 
        internalGetBidsFieldBuilder() {
      if (bidsBuilder_ == null) {
        bidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItem.Builder, com.mxc.push.common.protobuf.PublicAggreDepthV3ApiItemOrBuilder>(
                bids_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        bids_ = null;
      }
      return bidsBuilder_;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <code>string eventType = 3;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eventType = 3;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventType = 3;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string eventType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string eventType = 3;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object fromVersion_ = "";
    /**
     * <code>string fromVersion = 4;</code>
     * @return The fromVersion.
     */
    public java.lang.String getFromVersion() {
      java.lang.Object ref = fromVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fromVersion = 4;</code>
     * @return The bytes for fromVersion.
     */
    public com.google.protobuf.ByteString
        getFromVersionBytes() {
      java.lang.Object ref = fromVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fromVersion = 4;</code>
     * @param value The fromVersion to set.
     * @return This builder for chaining.
     */
    public Builder setFromVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fromVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string fromVersion = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromVersion() {
      fromVersion_ = getDefaultInstance().getFromVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string fromVersion = 4;</code>
     * @param value The bytes for fromVersion to set.
     * @return This builder for chaining.
     */
    public Builder setFromVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fromVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object toVersion_ = "";
    /**
     * <code>string toVersion = 5;</code>
     * @return The toVersion.
     */
    public java.lang.String getToVersion() {
      java.lang.Object ref = toVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string toVersion = 5;</code>
     * @return The bytes for toVersion.
     */
    public com.google.protobuf.ByteString
        getToVersionBytes() {
      java.lang.Object ref = toVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string toVersion = 5;</code>
     * @param value The toVersion to set.
     * @return This builder for chaining.
     */
    public Builder setToVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toVersion_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string toVersion = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearToVersion() {
      toVersion_ = getDefaultInstance().getToVersion();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string toVersion = 5;</code>
     * @param value The bytes for toVersion to set.
     * @return This builder for chaining.
     */
    public Builder setToVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toVersion_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PublicAggreDepthsV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicAggreDepthsV3Api)
  private static final com.mxc.push.common.protobuf.PublicAggreDepthsV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mxc.push.common.protobuf.PublicAggreDepthsV3Api();
  }

  public static com.mxc.push.common.protobuf.PublicAggreDepthsV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicAggreDepthsV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicAggreDepthsV3Api>() {
    @java.lang.Override
    public PublicAggreDepthsV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicAggreDepthsV3Api> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublicAggreDepthsV3Api> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicAggreDepthsV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

