// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicDealsV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public interface PublicDealsV3ApiItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicDealsV3ApiItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  java.lang.String getQuantity();
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  com.google.protobuf.ByteString
      getQuantityBytes();

  /**
   * <code>int32 tradeType = 3;</code>
   * @return The tradeType.
   */
  int getTradeType();

  /**
   * <code>int64 time = 4;</code>
   * @return The time.
   */
  long getTime();
}
