// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicBookTickerV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public final class PublicBookTickerV3ApiProto extends com.google.protobuf.GeneratedFile {
  private PublicBookTickerV3ApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PublicBookTickerV3ApiProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicBookTickerV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicBookTickerV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PublicBookTickerV3Api.proto\"e\n\025PublicB" +
      "ookTickerV3Api\022\020\n\010bidPrice\030\001 \001(\t\022\023\n\013bidQ" +
      "uantity\030\002 \001(\t\022\020\n\010askPrice\030\003 \001(\t\022\023\n\013askQu" +
      "antity\030\004 \001(\tB>\n\034com.mxc.push.common.prot" +
      "obufB\032PublicBookTickerV3ApiProtoH\001P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicBookTickerV3Api_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_PublicBookTickerV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PublicBookTickerV3Api_descriptor,
        new java.lang.String[] { "BidPrice", "BidQuantity", "AskPrice", "AskQuantity", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
