// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicMiniTickerV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicMiniTickerV3Api}
 */
@com.google.protobuf.Generated
public final class PublicMiniTickerV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicMiniTickerV3Api)
    PublicMiniTickerV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PublicMiniTickerV3Api");
  }
  // Use PublicMiniTickerV3Api.newBuilder() to construct.
  private PublicMiniTickerV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicMiniTickerV3Api() {
    symbol_ = "";
    price_ = "";
    rate_ = "";
    zonedRate_ = "";
    high_ = "";
    low_ = "";
    volume_ = "";
    quantity_ = "";
    lastCloseRate_ = "";
    lastCloseZonedRate_ = "";
    lastCloseHigh_ = "";
    lastCloseLow_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mxc.push.common.protobuf.PublicMiniTickerV3ApiProto.internal_static_PublicMiniTickerV3Api_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mxc.push.common.protobuf.PublicMiniTickerV3ApiProto.internal_static_PublicMiniTickerV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mxc.push.common.protobuf.PublicMiniTickerV3Api.class, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <pre>
   * 交易对名
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 交易对名
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object price_ = "";
  /**
   * <pre>
   * 最新价格
   * </pre>
   *
   * <code>string price = 2;</code>
   * @return The price.
   */
  @java.lang.Override
  public java.lang.String getPrice() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 最新价格
   * </pre>
   *
   * <code>string price = 2;</code>
   * @return The bytes for price.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPriceBytes() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rate_ = "";
  /**
   * <pre>
   * utc+8时区涨跌幅
   * </pre>
   *
   * <code>string rate = 3;</code>
   * @return The rate.
   */
  @java.lang.Override
  public java.lang.String getRate() {
    java.lang.Object ref = rate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * utc+8时区涨跌幅
   * </pre>
   *
   * <code>string rate = 3;</code>
   * @return The bytes for rate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRateBytes() {
    java.lang.Object ref = rate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ZONEDRATE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object zonedRate_ = "";
  /**
   * <pre>
   * 时区涨跌幅
   * </pre>
   *
   * <code>string zonedRate = 4;</code>
   * @return The zonedRate.
   */
  @java.lang.Override
  public java.lang.String getZonedRate() {
    java.lang.Object ref = zonedRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zonedRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 时区涨跌幅
   * </pre>
   *
   * <code>string zonedRate = 4;</code>
   * @return The bytes for zonedRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getZonedRateBytes() {
    java.lang.Object ref = zonedRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zonedRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGH_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object high_ = "";
  /**
   * <pre>
   * 滚动最高价
   * </pre>
   *
   * <code>string high = 5;</code>
   * @return The high.
   */
  @java.lang.Override
  public java.lang.String getHigh() {
    java.lang.Object ref = high_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      high_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 滚动最高价
   * </pre>
   *
   * <code>string high = 5;</code>
   * @return The bytes for high.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHighBytes() {
    java.lang.Object ref = high_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      high_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOW_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object low_ = "";
  /**
   * <pre>
   * 滚动最低价
   * </pre>
   *
   * <code>string low = 6;</code>
   * @return The low.
   */
  @java.lang.Override
  public java.lang.String getLow() {
    java.lang.Object ref = low_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      low_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 滚动最低价
   * </pre>
   *
   * <code>string low = 6;</code>
   * @return The bytes for low.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLowBytes() {
    java.lang.Object ref = low_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      low_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOLUME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object volume_ = "";
  /**
   * <pre>
   * 滚动成交额
   * </pre>
   *
   * <code>string volume = 7;</code>
   * @return The volume.
   */
  @java.lang.Override
  public java.lang.String getVolume() {
    java.lang.Object ref = volume_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      volume_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 滚动成交额
   * </pre>
   *
   * <code>string volume = 7;</code>
   * @return The bytes for volume.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVolumeBytes() {
    java.lang.Object ref = volume_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      volume_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quantity_ = "";
  /**
   * <pre>
   * 滚动成交量
   * </pre>
   *
   * <code>string quantity = 8;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public java.lang.String getQuantity() {
    java.lang.Object ref = quantity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quantity_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 滚动成交量
   * </pre>
   *
   * <code>string quantity = 8;</code>
   * @return The bytes for quantity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuantityBytes() {
    java.lang.Object ref = quantity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quantity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTCLOSERATE_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastCloseRate_ = "";
  /**
   * <pre>
   * utc+8时区上期收盘价模式涨跌幅
   * </pre>
   *
   * <code>string lastCloseRate = 9;</code>
   * @return The lastCloseRate.
   */
  @java.lang.Override
  public java.lang.String getLastCloseRate() {
    java.lang.Object ref = lastCloseRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastCloseRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * utc+8时区上期收盘价模式涨跌幅
   * </pre>
   *
   * <code>string lastCloseRate = 9;</code>
   * @return The bytes for lastCloseRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastCloseRateBytes() {
    java.lang.Object ref = lastCloseRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastCloseRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTCLOSEZONEDRATE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastCloseZonedRate_ = "";
  /**
   * <pre>
   * 上期收盘价模式时区涨跌幅
   * </pre>
   *
   * <code>string lastCloseZonedRate = 10;</code>
   * @return The lastCloseZonedRate.
   */
  @java.lang.Override
  public java.lang.String getLastCloseZonedRate() {
    java.lang.Object ref = lastCloseZonedRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastCloseZonedRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 上期收盘价模式时区涨跌幅
   * </pre>
   *
   * <code>string lastCloseZonedRate = 10;</code>
   * @return The bytes for lastCloseZonedRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastCloseZonedRateBytes() {
    java.lang.Object ref = lastCloseZonedRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastCloseZonedRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTCLOSEHIGH_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastCloseHigh_ = "";
  /**
   * <pre>
   * 上期收盘价模式滚动最高价
   * </pre>
   *
   * <code>string lastCloseHigh = 11;</code>
   * @return The lastCloseHigh.
   */
  @java.lang.Override
  public java.lang.String getLastCloseHigh() {
    java.lang.Object ref = lastCloseHigh_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastCloseHigh_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 上期收盘价模式滚动最高价
   * </pre>
   *
   * <code>string lastCloseHigh = 11;</code>
   * @return The bytes for lastCloseHigh.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastCloseHighBytes() {
    java.lang.Object ref = lastCloseHigh_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastCloseHigh_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTCLOSELOW_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastCloseLow_ = "";
  /**
   * <pre>
   * 上期收盘价模式滚动最低价
   * </pre>
   *
   * <code>string lastCloseLow = 12;</code>
   * @return The lastCloseLow.
   */
  @java.lang.Override
  public java.lang.String getLastCloseLow() {
    java.lang.Object ref = lastCloseLow_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastCloseLow_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 上期收盘价模式滚动最低价
   * </pre>
   *
   * <code>string lastCloseLow = 12;</code>
   * @return The bytes for lastCloseLow.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastCloseLowBytes() {
    java.lang.Object ref = lastCloseLow_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastCloseLow_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, rate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(zonedRate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, zonedRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(high_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, high_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(low_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, low_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(volume_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, volume_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseRate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, lastCloseRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseZonedRate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, lastCloseZonedRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseHigh_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, lastCloseHigh_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseLow_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, lastCloseLow_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, rate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(zonedRate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, zonedRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(high_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, high_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(low_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, low_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(volume_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, volume_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseRate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, lastCloseRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseZonedRate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, lastCloseZonedRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseHigh_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, lastCloseHigh_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastCloseLow_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, lastCloseLow_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mxc.push.common.protobuf.PublicMiniTickerV3Api)) {
      return super.equals(obj);
    }
    com.mxc.push.common.protobuf.PublicMiniTickerV3Api other = (com.mxc.push.common.protobuf.PublicMiniTickerV3Api) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getPrice()
        .equals(other.getPrice())) return false;
    if (!getRate()
        .equals(other.getRate())) return false;
    if (!getZonedRate()
        .equals(other.getZonedRate())) return false;
    if (!getHigh()
        .equals(other.getHigh())) return false;
    if (!getLow()
        .equals(other.getLow())) return false;
    if (!getVolume()
        .equals(other.getVolume())) return false;
    if (!getQuantity()
        .equals(other.getQuantity())) return false;
    if (!getLastCloseRate()
        .equals(other.getLastCloseRate())) return false;
    if (!getLastCloseZonedRate()
        .equals(other.getLastCloseZonedRate())) return false;
    if (!getLastCloseHigh()
        .equals(other.getLastCloseHigh())) return false;
    if (!getLastCloseLow()
        .equals(other.getLastCloseLow())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + getRate().hashCode();
    hash = (37 * hash) + ZONEDRATE_FIELD_NUMBER;
    hash = (53 * hash) + getZonedRate().hashCode();
    hash = (37 * hash) + HIGH_FIELD_NUMBER;
    hash = (53 * hash) + getHigh().hashCode();
    hash = (37 * hash) + LOW_FIELD_NUMBER;
    hash = (53 * hash) + getLow().hashCode();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getVolume().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity().hashCode();
    hash = (37 * hash) + LASTCLOSERATE_FIELD_NUMBER;
    hash = (53 * hash) + getLastCloseRate().hashCode();
    hash = (37 * hash) + LASTCLOSEZONEDRATE_FIELD_NUMBER;
    hash = (53 * hash) + getLastCloseZonedRate().hashCode();
    hash = (37 * hash) + LASTCLOSEHIGH_FIELD_NUMBER;
    hash = (53 * hash) + getLastCloseHigh().hashCode();
    hash = (37 * hash) + LASTCLOSELOW_FIELD_NUMBER;
    hash = (53 * hash) + getLastCloseLow().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mxc.push.common.protobuf.PublicMiniTickerV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicMiniTickerV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicMiniTickerV3Api)
      com.mxc.push.common.protobuf.PublicMiniTickerV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mxc.push.common.protobuf.PublicMiniTickerV3ApiProto.internal_static_PublicMiniTickerV3Api_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mxc.push.common.protobuf.PublicMiniTickerV3ApiProto.internal_static_PublicMiniTickerV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mxc.push.common.protobuf.PublicMiniTickerV3Api.class, com.mxc.push.common.protobuf.PublicMiniTickerV3Api.Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicMiniTickerV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      price_ = "";
      rate_ = "";
      zonedRate_ = "";
      high_ = "";
      low_ = "";
      volume_ = "";
      quantity_ = "";
      lastCloseRate_ = "";
      lastCloseZonedRate_ = "";
      lastCloseHigh_ = "";
      lastCloseLow_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mxc.push.common.protobuf.PublicMiniTickerV3ApiProto.internal_static_PublicMiniTickerV3Api_descriptor;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api getDefaultInstanceForType() {
      return com.mxc.push.common.protobuf.PublicMiniTickerV3Api.getDefaultInstance();
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api build() {
      com.mxc.push.common.protobuf.PublicMiniTickerV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicMiniTickerV3Api buildPartial() {
      com.mxc.push.common.protobuf.PublicMiniTickerV3Api result = new com.mxc.push.common.protobuf.PublicMiniTickerV3Api(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mxc.push.common.protobuf.PublicMiniTickerV3Api result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rate_ = rate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.zonedRate_ = zonedRate_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.high_ = high_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.low_ = low_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.volume_ = volume_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.lastCloseRate_ = lastCloseRate_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.lastCloseZonedRate_ = lastCloseZonedRate_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.lastCloseHigh_ = lastCloseHigh_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.lastCloseLow_ = lastCloseLow_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mxc.push.common.protobuf.PublicMiniTickerV3Api) {
        return mergeFrom((com.mxc.push.common.protobuf.PublicMiniTickerV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mxc.push.common.protobuf.PublicMiniTickerV3Api other) {
      if (other == com.mxc.push.common.protobuf.PublicMiniTickerV3Api.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getRate().isEmpty()) {
        rate_ = other.rate_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getZonedRate().isEmpty()) {
        zonedRate_ = other.zonedRate_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getHigh().isEmpty()) {
        high_ = other.high_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getLow().isEmpty()) {
        low_ = other.low_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getVolume().isEmpty()) {
        volume_ = other.volume_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getQuantity().isEmpty()) {
        quantity_ = other.quantity_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getLastCloseRate().isEmpty()) {
        lastCloseRate_ = other.lastCloseRate_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getLastCloseZonedRate().isEmpty()) {
        lastCloseZonedRate_ = other.lastCloseZonedRate_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getLastCloseHigh().isEmpty()) {
        lastCloseHigh_ = other.lastCloseHigh_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getLastCloseLow().isEmpty()) {
        lastCloseLow_ = other.lastCloseLow_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              price_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              rate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              zonedRate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              high_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              low_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              volume_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              quantity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              lastCloseRate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              lastCloseZonedRate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              lastCloseHigh_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              lastCloseLow_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * 交易对名
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 交易对名
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 交易对名
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易对名
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易对名
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object price_ = "";
    /**
     * <pre>
     * 最新价格
     * </pre>
     *
     * <code>string price = 2;</code>
     * @return The price.
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 最新价格
     * </pre>
     *
     * <code>string price = 2;</code>
     * @return The bytes for price.
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 最新价格
     * </pre>
     *
     * <code>string price = 2;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      price_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最新价格
     * </pre>
     *
     * <code>string price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      price_ = getDefaultInstance().getPrice();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最新价格
     * </pre>
     *
     * <code>string price = 2;</code>
     * @param value The bytes for price to set.
     * @return This builder for chaining.
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      price_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object rate_ = "";
    /**
     * <pre>
     * utc+8时区涨跌幅
     * </pre>
     *
     * <code>string rate = 3;</code>
     * @return The rate.
     */
    public java.lang.String getRate() {
      java.lang.Object ref = rate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * utc+8时区涨跌幅
     * </pre>
     *
     * <code>string rate = 3;</code>
     * @return The bytes for rate.
     */
    public com.google.protobuf.ByteString
        getRateBytes() {
      java.lang.Object ref = rate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * utc+8时区涨跌幅
     * </pre>
     *
     * <code>string rate = 3;</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * utc+8时区涨跌幅
     * </pre>
     *
     * <code>string rate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      rate_ = getDefaultInstance().getRate();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * utc+8时区涨跌幅
     * </pre>
     *
     * <code>string rate = 3;</code>
     * @param value The bytes for rate to set.
     * @return This builder for chaining.
     */
    public Builder setRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object zonedRate_ = "";
    /**
     * <pre>
     * 时区涨跌幅
     * </pre>
     *
     * <code>string zonedRate = 4;</code>
     * @return The zonedRate.
     */
    public java.lang.String getZonedRate() {
      java.lang.Object ref = zonedRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zonedRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 时区涨跌幅
     * </pre>
     *
     * <code>string zonedRate = 4;</code>
     * @return The bytes for zonedRate.
     */
    public com.google.protobuf.ByteString
        getZonedRateBytes() {
      java.lang.Object ref = zonedRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zonedRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 时区涨跌幅
     * </pre>
     *
     * <code>string zonedRate = 4;</code>
     * @param value The zonedRate to set.
     * @return This builder for chaining.
     */
    public Builder setZonedRate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      zonedRate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时区涨跌幅
     * </pre>
     *
     * <code>string zonedRate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearZonedRate() {
      zonedRate_ = getDefaultInstance().getZonedRate();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时区涨跌幅
     * </pre>
     *
     * <code>string zonedRate = 4;</code>
     * @param value The bytes for zonedRate to set.
     * @return This builder for chaining.
     */
    public Builder setZonedRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      zonedRate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object high_ = "";
    /**
     * <pre>
     * 滚动最高价
     * </pre>
     *
     * <code>string high = 5;</code>
     * @return The high.
     */
    public java.lang.String getHigh() {
      java.lang.Object ref = high_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        high_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 滚动最高价
     * </pre>
     *
     * <code>string high = 5;</code>
     * @return The bytes for high.
     */
    public com.google.protobuf.ByteString
        getHighBytes() {
      java.lang.Object ref = high_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        high_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 滚动最高价
     * </pre>
     *
     * <code>string high = 5;</code>
     * @param value The high to set.
     * @return This builder for chaining.
     */
    public Builder setHigh(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      high_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动最高价
     * </pre>
     *
     * <code>string high = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHigh() {
      high_ = getDefaultInstance().getHigh();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动最高价
     * </pre>
     *
     * <code>string high = 5;</code>
     * @param value The bytes for high to set.
     * @return This builder for chaining.
     */
    public Builder setHighBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      high_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object low_ = "";
    /**
     * <pre>
     * 滚动最低价
     * </pre>
     *
     * <code>string low = 6;</code>
     * @return The low.
     */
    public java.lang.String getLow() {
      java.lang.Object ref = low_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        low_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 滚动最低价
     * </pre>
     *
     * <code>string low = 6;</code>
     * @return The bytes for low.
     */
    public com.google.protobuf.ByteString
        getLowBytes() {
      java.lang.Object ref = low_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        low_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 滚动最低价
     * </pre>
     *
     * <code>string low = 6;</code>
     * @param value The low to set.
     * @return This builder for chaining.
     */
    public Builder setLow(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      low_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动最低价
     * </pre>
     *
     * <code>string low = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLow() {
      low_ = getDefaultInstance().getLow();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动最低价
     * </pre>
     *
     * <code>string low = 6;</code>
     * @param value The bytes for low to set.
     * @return This builder for chaining.
     */
    public Builder setLowBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      low_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object volume_ = "";
    /**
     * <pre>
     * 滚动成交额
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @return The volume.
     */
    public java.lang.String getVolume() {
      java.lang.Object ref = volume_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        volume_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 滚动成交额
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @return The bytes for volume.
     */
    public com.google.protobuf.ByteString
        getVolumeBytes() {
      java.lang.Object ref = volume_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        volume_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 滚动成交额
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      volume_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动成交额
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      volume_ = getDefaultInstance().getVolume();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动成交额
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @param value The bytes for volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      volume_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object quantity_ = "";
    /**
     * <pre>
     * 滚动成交量
     * </pre>
     *
     * <code>string quantity = 8;</code>
     * @return The quantity.
     */
    public java.lang.String getQuantity() {
      java.lang.Object ref = quantity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quantity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 滚动成交量
     * </pre>
     *
     * <code>string quantity = 8;</code>
     * @return The bytes for quantity.
     */
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      java.lang.Object ref = quantity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quantity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 滚动成交量
     * </pre>
     *
     * <code>string quantity = 8;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quantity_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动成交量
     * </pre>
     *
     * <code>string quantity = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      quantity_ = getDefaultInstance().getQuantity();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 滚动成交量
     * </pre>
     *
     * <code>string quantity = 8;</code>
     * @param value The bytes for quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quantity_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object lastCloseRate_ = "";
    /**
     * <pre>
     * utc+8时区上期收盘价模式涨跌幅
     * </pre>
     *
     * <code>string lastCloseRate = 9;</code>
     * @return The lastCloseRate.
     */
    public java.lang.String getLastCloseRate() {
      java.lang.Object ref = lastCloseRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastCloseRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * utc+8时区上期收盘价模式涨跌幅
     * </pre>
     *
     * <code>string lastCloseRate = 9;</code>
     * @return The bytes for lastCloseRate.
     */
    public com.google.protobuf.ByteString
        getLastCloseRateBytes() {
      java.lang.Object ref = lastCloseRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastCloseRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * utc+8时区上期收盘价模式涨跌幅
     * </pre>
     *
     * <code>string lastCloseRate = 9;</code>
     * @param value The lastCloseRate to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseRate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastCloseRate_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * utc+8时区上期收盘价模式涨跌幅
     * </pre>
     *
     * <code>string lastCloseRate = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCloseRate() {
      lastCloseRate_ = getDefaultInstance().getLastCloseRate();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * utc+8时区上期收盘价模式涨跌幅
     * </pre>
     *
     * <code>string lastCloseRate = 9;</code>
     * @param value The bytes for lastCloseRate to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastCloseRate_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object lastCloseZonedRate_ = "";
    /**
     * <pre>
     * 上期收盘价模式时区涨跌幅
     * </pre>
     *
     * <code>string lastCloseZonedRate = 10;</code>
     * @return The lastCloseZonedRate.
     */
    public java.lang.String getLastCloseZonedRate() {
      java.lang.Object ref = lastCloseZonedRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastCloseZonedRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 上期收盘价模式时区涨跌幅
     * </pre>
     *
     * <code>string lastCloseZonedRate = 10;</code>
     * @return The bytes for lastCloseZonedRate.
     */
    public com.google.protobuf.ByteString
        getLastCloseZonedRateBytes() {
      java.lang.Object ref = lastCloseZonedRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastCloseZonedRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 上期收盘价模式时区涨跌幅
     * </pre>
     *
     * <code>string lastCloseZonedRate = 10;</code>
     * @param value The lastCloseZonedRate to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseZonedRate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastCloseZonedRate_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上期收盘价模式时区涨跌幅
     * </pre>
     *
     * <code>string lastCloseZonedRate = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCloseZonedRate() {
      lastCloseZonedRate_ = getDefaultInstance().getLastCloseZonedRate();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上期收盘价模式时区涨跌幅
     * </pre>
     *
     * <code>string lastCloseZonedRate = 10;</code>
     * @param value The bytes for lastCloseZonedRate to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseZonedRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastCloseZonedRate_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object lastCloseHigh_ = "";
    /**
     * <pre>
     * 上期收盘价模式滚动最高价
     * </pre>
     *
     * <code>string lastCloseHigh = 11;</code>
     * @return The lastCloseHigh.
     */
    public java.lang.String getLastCloseHigh() {
      java.lang.Object ref = lastCloseHigh_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastCloseHigh_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最高价
     * </pre>
     *
     * <code>string lastCloseHigh = 11;</code>
     * @return The bytes for lastCloseHigh.
     */
    public com.google.protobuf.ByteString
        getLastCloseHighBytes() {
      java.lang.Object ref = lastCloseHigh_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastCloseHigh_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最高价
     * </pre>
     *
     * <code>string lastCloseHigh = 11;</code>
     * @param value The lastCloseHigh to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseHigh(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastCloseHigh_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最高价
     * </pre>
     *
     * <code>string lastCloseHigh = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCloseHigh() {
      lastCloseHigh_ = getDefaultInstance().getLastCloseHigh();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最高价
     * </pre>
     *
     * <code>string lastCloseHigh = 11;</code>
     * @param value The bytes for lastCloseHigh to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseHighBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastCloseHigh_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object lastCloseLow_ = "";
    /**
     * <pre>
     * 上期收盘价模式滚动最低价
     * </pre>
     *
     * <code>string lastCloseLow = 12;</code>
     * @return The lastCloseLow.
     */
    public java.lang.String getLastCloseLow() {
      java.lang.Object ref = lastCloseLow_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastCloseLow_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最低价
     * </pre>
     *
     * <code>string lastCloseLow = 12;</code>
     * @return The bytes for lastCloseLow.
     */
    public com.google.protobuf.ByteString
        getLastCloseLowBytes() {
      java.lang.Object ref = lastCloseLow_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastCloseLow_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最低价
     * </pre>
     *
     * <code>string lastCloseLow = 12;</code>
     * @param value The lastCloseLow to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseLow(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastCloseLow_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最低价
     * </pre>
     *
     * <code>string lastCloseLow = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCloseLow() {
      lastCloseLow_ = getDefaultInstance().getLastCloseLow();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上期收盘价模式滚动最低价
     * </pre>
     *
     * <code>string lastCloseLow = 12;</code>
     * @param value The bytes for lastCloseLow to set.
     * @return This builder for chaining.
     */
    public Builder setLastCloseLowBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastCloseLow_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PublicMiniTickerV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicMiniTickerV3Api)
  private static final com.mxc.push.common.protobuf.PublicMiniTickerV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mxc.push.common.protobuf.PublicMiniTickerV3Api();
  }

  public static com.mxc.push.common.protobuf.PublicMiniTickerV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicMiniTickerV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicMiniTickerV3Api>() {
    @java.lang.Override
    public PublicMiniTickerV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicMiniTickerV3Api> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublicMiniTickerV3Api> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicMiniTickerV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

