// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicDealsV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public interface PublicDealsV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicDealsV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  java.util.List<com.mxc.push.common.protobuf.PublicDealsV3ApiItem> 
      getDealsList();
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicDealsV3ApiItem getDeals(int index);
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  int getDealsCount();
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  java.util.List<? extends com.mxc.push.common.protobuf.PublicDealsV3ApiItemOrBuilder> 
      getDealsOrBuilderList();
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicDealsV3ApiItemOrBuilder getDealsOrBuilder(
      int index);

  /**
   * <code>string eventType = 2;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <code>string eventType = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();
}
