// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicSpotKlineV3Api.proto
// Protobuf Java Version: 4.33.2

package com.mxc.push.common.protobuf;

/**
 * Protobuf type {@code PublicSpotKlineV3Api}
 */
@com.google.protobuf.Generated
public final class PublicSpotKlineV3Api extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PublicSpotKlineV3Api)
    PublicSpotKlineV3ApiOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PublicSpotKlineV3Api");
  }
  // Use PublicSpotKlineV3Api.newBuilder() to construct.
  private PublicSpotKlineV3Api(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublicSpotKlineV3Api() {
    interval_ = "";
    openingPrice_ = "";
    closingPrice_ = "";
    highestPrice_ = "";
    lowestPrice_ = "";
    volume_ = "";
    amount_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mxc.push.common.protobuf.PublicSpotKlineV3ApiProto.internal_static_PublicSpotKlineV3Api_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mxc.push.common.protobuf.PublicSpotKlineV3ApiProto.internal_static_PublicSpotKlineV3Api_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mxc.push.common.protobuf.PublicSpotKlineV3Api.class, com.mxc.push.common.protobuf.PublicSpotKlineV3Api.Builder.class);
  }

  public static final int INTERVAL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object interval_ = "";
  /**
   * <pre>
   * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
   * </pre>
   *
   * <code>string interval = 1;</code>
   * @return The interval.
   */
  @java.lang.Override
  public java.lang.String getInterval() {
    java.lang.Object ref = interval_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interval_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
   * </pre>
   *
   * <code>string interval = 1;</code>
   * @return The bytes for interval.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIntervalBytes() {
    java.lang.Object ref = interval_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interval_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WINDOWSTART_FIELD_NUMBER = 2;
  private long windowStart_ = 0L;
  /**
   * <pre>
   * 窗口开始时间戳(秒时间戳)
   * </pre>
   *
   * <code>int64 windowStart = 2;</code>
   * @return The windowStart.
   */
  @java.lang.Override
  public long getWindowStart() {
    return windowStart_;
  }

  public static final int OPENINGPRICE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object openingPrice_ = "";
  /**
   * <pre>
   * 开盘价
   * </pre>
   *
   * <code>string openingPrice = 3;</code>
   * @return The openingPrice.
   */
  @java.lang.Override
  public java.lang.String getOpeningPrice() {
    java.lang.Object ref = openingPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      openingPrice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 开盘价
   * </pre>
   *
   * <code>string openingPrice = 3;</code>
   * @return The bytes for openingPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOpeningPriceBytes() {
    java.lang.Object ref = openingPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      openingPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOSINGPRICE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object closingPrice_ = "";
  /**
   * <pre>
   * 收盘价
   * </pre>
   *
   * <code>string closingPrice = 4;</code>
   * @return The closingPrice.
   */
  @java.lang.Override
  public java.lang.String getClosingPrice() {
    java.lang.Object ref = closingPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      closingPrice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 收盘价
   * </pre>
   *
   * <code>string closingPrice = 4;</code>
   * @return The bytes for closingPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClosingPriceBytes() {
    java.lang.Object ref = closingPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      closingPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGHESTPRICE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object highestPrice_ = "";
  /**
   * <pre>
   * 最高价
   * </pre>
   *
   * <code>string highestPrice = 5;</code>
   * @return The highestPrice.
   */
  @java.lang.Override
  public java.lang.String getHighestPrice() {
    java.lang.Object ref = highestPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      highestPrice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 最高价
   * </pre>
   *
   * <code>string highestPrice = 5;</code>
   * @return The bytes for highestPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHighestPriceBytes() {
    java.lang.Object ref = highestPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      highestPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOWESTPRICE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lowestPrice_ = "";
  /**
   * <pre>
   * 最低价
   * </pre>
   *
   * <code>string lowestPrice = 6;</code>
   * @return The lowestPrice.
   */
  @java.lang.Override
  public java.lang.String getLowestPrice() {
    java.lang.Object ref = lowestPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lowestPrice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 最低价
   * </pre>
   *
   * <code>string lowestPrice = 6;</code>
   * @return The bytes for lowestPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLowestPriceBytes() {
    java.lang.Object ref = lowestPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lowestPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOLUME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object volume_ = "";
  /**
   * <pre>
   * 成交量
   * </pre>
   *
   * <code>string volume = 7;</code>
   * @return The volume.
   */
  @java.lang.Override
  public java.lang.String getVolume() {
    java.lang.Object ref = volume_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      volume_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 成交量
   * </pre>
   *
   * <code>string volume = 7;</code>
   * @return The bytes for volume.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVolumeBytes() {
    java.lang.Object ref = volume_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      volume_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object amount_ = "";
  /**
   * <pre>
   * 成交额
   * </pre>
   *
   * <code>string amount = 8;</code>
   * @return The amount.
   */
  @java.lang.Override
  public java.lang.String getAmount() {
    java.lang.Object ref = amount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      amount_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 成交额
   * </pre>
   *
   * <code>string amount = 8;</code>
   * @return The bytes for amount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAmountBytes() {
    java.lang.Object ref = amount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      amount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WINDOWEND_FIELD_NUMBER = 9;
  private long windowEnd_ = 0L;
  /**
   * <pre>
   * 窗口结束时间戳(秒时间戳)
   * </pre>
   *
   * <code>int64 windowEnd = 9;</code>
   * @return The windowEnd.
   */
  @java.lang.Override
  public long getWindowEnd() {
    return windowEnd_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(interval_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, interval_);
    }
    if (windowStart_ != 0L) {
      output.writeInt64(2, windowStart_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(openingPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, openingPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(closingPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, closingPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(highestPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, highestPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lowestPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, lowestPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(volume_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, volume_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(amount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, amount_);
    }
    if (windowEnd_ != 0L) {
      output.writeInt64(9, windowEnd_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(interval_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, interval_);
    }
    if (windowStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, windowStart_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(openingPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, openingPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(closingPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, closingPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(highestPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, highestPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lowestPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, lowestPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(volume_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, volume_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(amount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, amount_);
    }
    if (windowEnd_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, windowEnd_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mxc.push.common.protobuf.PublicSpotKlineV3Api)) {
      return super.equals(obj);
    }
    com.mxc.push.common.protobuf.PublicSpotKlineV3Api other = (com.mxc.push.common.protobuf.PublicSpotKlineV3Api) obj;

    if (!getInterval()
        .equals(other.getInterval())) return false;
    if (getWindowStart()
        != other.getWindowStart()) return false;
    if (!getOpeningPrice()
        .equals(other.getOpeningPrice())) return false;
    if (!getClosingPrice()
        .equals(other.getClosingPrice())) return false;
    if (!getHighestPrice()
        .equals(other.getHighestPrice())) return false;
    if (!getLowestPrice()
        .equals(other.getLowestPrice())) return false;
    if (!getVolume()
        .equals(other.getVolume())) return false;
    if (!getAmount()
        .equals(other.getAmount())) return false;
    if (getWindowEnd()
        != other.getWindowEnd()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getInterval().hashCode();
    hash = (37 * hash) + WINDOWSTART_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWindowStart());
    hash = (37 * hash) + OPENINGPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getOpeningPrice().hashCode();
    hash = (37 * hash) + CLOSINGPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getClosingPrice().hashCode();
    hash = (37 * hash) + HIGHESTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getHighestPrice().hashCode();
    hash = (37 * hash) + LOWESTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getLowestPrice().hashCode();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getVolume().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount().hashCode();
    hash = (37 * hash) + WINDOWEND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWindowEnd());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mxc.push.common.protobuf.PublicSpotKlineV3Api prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PublicSpotKlineV3Api}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PublicSpotKlineV3Api)
      com.mxc.push.common.protobuf.PublicSpotKlineV3ApiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mxc.push.common.protobuf.PublicSpotKlineV3ApiProto.internal_static_PublicSpotKlineV3Api_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mxc.push.common.protobuf.PublicSpotKlineV3ApiProto.internal_static_PublicSpotKlineV3Api_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mxc.push.common.protobuf.PublicSpotKlineV3Api.class, com.mxc.push.common.protobuf.PublicSpotKlineV3Api.Builder.class);
    }

    // Construct using com.mxc.push.common.protobuf.PublicSpotKlineV3Api.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      interval_ = "";
      windowStart_ = 0L;
      openingPrice_ = "";
      closingPrice_ = "";
      highestPrice_ = "";
      lowestPrice_ = "";
      volume_ = "";
      amount_ = "";
      windowEnd_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mxc.push.common.protobuf.PublicSpotKlineV3ApiProto.internal_static_PublicSpotKlineV3Api_descriptor;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicSpotKlineV3Api getDefaultInstanceForType() {
      return com.mxc.push.common.protobuf.PublicSpotKlineV3Api.getDefaultInstance();
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicSpotKlineV3Api build() {
      com.mxc.push.common.protobuf.PublicSpotKlineV3Api result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mxc.push.common.protobuf.PublicSpotKlineV3Api buildPartial() {
      com.mxc.push.common.protobuf.PublicSpotKlineV3Api result = new com.mxc.push.common.protobuf.PublicSpotKlineV3Api(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mxc.push.common.protobuf.PublicSpotKlineV3Api result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.interval_ = interval_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.windowStart_ = windowStart_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.openingPrice_ = openingPrice_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.closingPrice_ = closingPrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.highestPrice_ = highestPrice_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lowestPrice_ = lowestPrice_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.volume_ = volume_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.windowEnd_ = windowEnd_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mxc.push.common.protobuf.PublicSpotKlineV3Api) {
        return mergeFrom((com.mxc.push.common.protobuf.PublicSpotKlineV3Api)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mxc.push.common.protobuf.PublicSpotKlineV3Api other) {
      if (other == com.mxc.push.common.protobuf.PublicSpotKlineV3Api.getDefaultInstance()) return this;
      if (!other.getInterval().isEmpty()) {
        interval_ = other.interval_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getWindowStart() != 0L) {
        setWindowStart(other.getWindowStart());
      }
      if (!other.getOpeningPrice().isEmpty()) {
        openingPrice_ = other.openingPrice_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getClosingPrice().isEmpty()) {
        closingPrice_ = other.closingPrice_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getHighestPrice().isEmpty()) {
        highestPrice_ = other.highestPrice_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getLowestPrice().isEmpty()) {
        lowestPrice_ = other.lowestPrice_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getVolume().isEmpty()) {
        volume_ = other.volume_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getAmount().isEmpty()) {
        amount_ = other.amount_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getWindowEnd() != 0L) {
        setWindowEnd(other.getWindowEnd());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              interval_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              windowStart_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              openingPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              closingPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              highestPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              lowestPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              volume_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              amount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              windowEnd_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object interval_ = "";
    /**
     * <pre>
     * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
     * </pre>
     *
     * <code>string interval = 1;</code>
     * @return The interval.
     */
    public java.lang.String getInterval() {
      java.lang.Object ref = interval_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interval_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
     * </pre>
     *
     * <code>string interval = 1;</code>
     * @return The bytes for interval.
     */
    public com.google.protobuf.ByteString
        getIntervalBytes() {
      java.lang.Object ref = interval_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
     * </pre>
     *
     * <code>string interval = 1;</code>
     * @param value The interval to set.
     * @return This builder for chaining.
     */
    public Builder setInterval(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      interval_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
     * </pre>
     *
     * <code>string interval = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterval() {
      interval_ = getDefaultInstance().getInterval();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
     * </pre>
     *
     * <code>string interval = 1;</code>
     * @param value The bytes for interval to set.
     * @return This builder for chaining.
     */
    public Builder setIntervalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      interval_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long windowStart_ ;
    /**
     * <pre>
     * 窗口开始时间戳(秒时间戳)
     * </pre>
     *
     * <code>int64 windowStart = 2;</code>
     * @return The windowStart.
     */
    @java.lang.Override
    public long getWindowStart() {
      return windowStart_;
    }
    /**
     * <pre>
     * 窗口开始时间戳(秒时间戳)
     * </pre>
     *
     * <code>int64 windowStart = 2;</code>
     * @param value The windowStart to set.
     * @return This builder for chaining.
     */
    public Builder setWindowStart(long value) {

      windowStart_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 窗口开始时间戳(秒时间戳)
     * </pre>
     *
     * <code>int64 windowStart = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowStart() {
      bitField0_ = (bitField0_ & ~0x00000002);
      windowStart_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object openingPrice_ = "";
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>string openingPrice = 3;</code>
     * @return The openingPrice.
     */
    public java.lang.String getOpeningPrice() {
      java.lang.Object ref = openingPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        openingPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>string openingPrice = 3;</code>
     * @return The bytes for openingPrice.
     */
    public com.google.protobuf.ByteString
        getOpeningPriceBytes() {
      java.lang.Object ref = openingPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openingPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>string openingPrice = 3;</code>
     * @param value The openingPrice to set.
     * @return This builder for chaining.
     */
    public Builder setOpeningPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      openingPrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>string openingPrice = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpeningPrice() {
      openingPrice_ = getDefaultInstance().getOpeningPrice();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>string openingPrice = 3;</code>
     * @param value The bytes for openingPrice to set.
     * @return This builder for chaining.
     */
    public Builder setOpeningPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      openingPrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object closingPrice_ = "";
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>string closingPrice = 4;</code>
     * @return The closingPrice.
     */
    public java.lang.String getClosingPrice() {
      java.lang.Object ref = closingPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        closingPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>string closingPrice = 4;</code>
     * @return The bytes for closingPrice.
     */
    public com.google.protobuf.ByteString
        getClosingPriceBytes() {
      java.lang.Object ref = closingPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        closingPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>string closingPrice = 4;</code>
     * @param value The closingPrice to set.
     * @return This builder for chaining.
     */
    public Builder setClosingPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      closingPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>string closingPrice = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClosingPrice() {
      closingPrice_ = getDefaultInstance().getClosingPrice();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>string closingPrice = 4;</code>
     * @param value The bytes for closingPrice to set.
     * @return This builder for chaining.
     */
    public Builder setClosingPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      closingPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object highestPrice_ = "";
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>string highestPrice = 5;</code>
     * @return The highestPrice.
     */
    public java.lang.String getHighestPrice() {
      java.lang.Object ref = highestPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        highestPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>string highestPrice = 5;</code>
     * @return The bytes for highestPrice.
     */
    public com.google.protobuf.ByteString
        getHighestPriceBytes() {
      java.lang.Object ref = highestPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        highestPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>string highestPrice = 5;</code>
     * @param value The highestPrice to set.
     * @return This builder for chaining.
     */
    public Builder setHighestPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      highestPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>string highestPrice = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHighestPrice() {
      highestPrice_ = getDefaultInstance().getHighestPrice();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>string highestPrice = 5;</code>
     * @param value The bytes for highestPrice to set.
     * @return This builder for chaining.
     */
    public Builder setHighestPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      highestPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object lowestPrice_ = "";
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>string lowestPrice = 6;</code>
     * @return The lowestPrice.
     */
    public java.lang.String getLowestPrice() {
      java.lang.Object ref = lowestPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lowestPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>string lowestPrice = 6;</code>
     * @return The bytes for lowestPrice.
     */
    public com.google.protobuf.ByteString
        getLowestPriceBytes() {
      java.lang.Object ref = lowestPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lowestPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>string lowestPrice = 6;</code>
     * @param value The lowestPrice to set.
     * @return This builder for chaining.
     */
    public Builder setLowestPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lowestPrice_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>string lowestPrice = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLowestPrice() {
      lowestPrice_ = getDefaultInstance().getLowestPrice();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>string lowestPrice = 6;</code>
     * @param value The bytes for lowestPrice to set.
     * @return This builder for chaining.
     */
    public Builder setLowestPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lowestPrice_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object volume_ = "";
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @return The volume.
     */
    public java.lang.String getVolume() {
      java.lang.Object ref = volume_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        volume_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @return The bytes for volume.
     */
    public com.google.protobuf.ByteString
        getVolumeBytes() {
      java.lang.Object ref = volume_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        volume_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      volume_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      volume_ = getDefaultInstance().getVolume();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>string volume = 7;</code>
     * @param value The bytes for volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      volume_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object amount_ = "";
    /**
     * <pre>
     * 成交额
     * </pre>
     *
     * <code>string amount = 8;</code>
     * @return The amount.
     */
    public java.lang.String getAmount() {
      java.lang.Object ref = amount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 成交额
     * </pre>
     *
     * <code>string amount = 8;</code>
     * @return The bytes for amount.
     */
    public com.google.protobuf.ByteString
        getAmountBytes() {
      java.lang.Object ref = amount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 成交额
     * </pre>
     *
     * <code>string amount = 8;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      amount_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成交额
     * </pre>
     *
     * <code>string amount = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      amount_ = getDefaultInstance().getAmount();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成交额
     * </pre>
     *
     * <code>string amount = 8;</code>
     * @param value The bytes for amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      amount_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private long windowEnd_ ;
    /**
     * <pre>
     * 窗口结束时间戳(秒时间戳)
     * </pre>
     *
     * <code>int64 windowEnd = 9;</code>
     * @return The windowEnd.
     */
    @java.lang.Override
    public long getWindowEnd() {
      return windowEnd_;
    }
    /**
     * <pre>
     * 窗口结束时间戳(秒时间戳)
     * </pre>
     *
     * <code>int64 windowEnd = 9;</code>
     * @param value The windowEnd to set.
     * @return This builder for chaining.
     */
    public Builder setWindowEnd(long value) {

      windowEnd_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 窗口结束时间戳(秒时间戳)
     * </pre>
     *
     * <code>int64 windowEnd = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowEnd() {
      bitField0_ = (bitField0_ & ~0x00000100);
      windowEnd_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PublicSpotKlineV3Api)
  }

  // @@protoc_insertion_point(class_scope:PublicSpotKlineV3Api)
  private static final com.mxc.push.common.protobuf.PublicSpotKlineV3Api DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mxc.push.common.protobuf.PublicSpotKlineV3Api();
  }

  public static com.mxc.push.common.protobuf.PublicSpotKlineV3Api getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicSpotKlineV3Api>
      PARSER = new com.google.protobuf.AbstractParser<PublicSpotKlineV3Api>() {
    @java.lang.Override
    public PublicSpotKlineV3Api parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublicSpotKlineV3Api> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublicSpotKlineV3Api> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mxc.push.common.protobuf.PublicSpotKlineV3Api getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

